# Generated by Django 4.0 on 2021-12-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название парковочного места')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateTimeField(verbose_name='Время прибытия')),
                ('departure', models.DateTimeField(verbose_name='Время отъезда')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parking', verbose_name='Парковочное место')),
            ],
            options={
                'ordering': ['-arrival'],
            },
        ),
    ]
