# Generated by Django 4.0 on 2021-12-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Название парковочного места'),
        ),
    ]
